apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-app
  labels:
    app: country-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: country-app
  template:
    metadata:
      labels:
        app: country-app
      annotations:
        version: "${ci_commit_sha}"
    spec:
      containers:
        - name: country-app
          image: sentidas1/country-service:b6fa4ef682cce30a56793e93d765a0b2d1081104
          ports:
            - containerPort: 8088
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"